package main

func init() {
	register("de", map[string]string{
		"layout.datetime": "02.01.2006 15:04",
		"layout.date":     "02.01.2006",
		"layout.day":      "02.01.",
		"unit.min":        "Min.",
		"unit.h":          "Std.",
		"unit.d":          "Tg.",

		"cmd.menu":     "Hauptmenü",
		"cmd.list":     "Meine Monitore",
		"cmd.add":      "Monitor hinzufügen",
		"cmd.language": "Sprache",
		"cmd.help":     "Hilfe",
		"cmd.premium":  "Tarif Premium",
		"cmd.invite":   "Freunde einladen",

		"lang.pick": "Select your language\nВыберите язык\nОберіть мову\nSprache wählen\nSeleccione el idioma",

		"btn.menu":          "Hauptmenü",
		"btn.back":          "Zurück",
		"btn.cancel":        "Abbrechen",
		"btn.list":          "Meine Monitore",
		"btn.add":           "Monitor hinzufügen",
		"btn.help":          "Hilfe",
		"btn.premium":       "Premium",
		"btn.language":      "Sprache",
		"btn.refresh":       "Aktualisieren",
		"btn.history":       "Verlauf",
		"btn.thresholds":    "Schwellenwerte",
		"btn.install":       "Installationsbefehl",
		"btn.delete":        "Löschen",
		"btn.tolist":        "Zur Liste",
		"btn.open":          "Monitor öffnen",
		"btn.pay":           "%d Stars bezahlen",
		"btn.chats":         "Weitere Chats",
		"btn.change":        "Ändern",
		"btn.clear":         "Leeren",
		"btn.about_premium": "Über Premium",
		"btn.t.http":        "Website (HTTP)",
		"btn.t.hb":          "Geplante Aufgabe",
		"btn.t.ssl":         "SSL-Zertifikat",
		"btn.t.ag":          "Server",
		"btn.thr_cpu":       "CPU %.0f%%",
		"btn.thr_ram":       "RAM %.0f%%",
		"btn.thr_disk":      "Festplatte %.0f%%",

		"menu.title":   "<b>UptimeAnt</b>\nIch behalte Ihre Websites, geplante Aufgaben, SSL-Zertifikate und Server im Blick und schreibe Ihnen hier, sobald etwas ausfällt.",
		"menu.none":    "Sie haben noch keine Monitore. Fügen Sie den ersten hinzu, das dauert eine Minute.",
		"menu.summary": "🟢 In Betrieb %d   🔴 Gestört %d   ⚪ Wartend %d",

		"help.text": "<b>❓ Hilfe</b>\nUptimeAnt behält Ihre Ressourcen im Blick und schreibt Ihnen hier, wenn etwas ausfällt und wenn alles wieder läuft.\n\n<b>So funktioniert es</b>\n1. Tippen Sie auf „Monitor hinzufügen“.\n2. Wählen Sie, was überwacht werden soll.\n3. Folgen Sie den kurzen Hinweisen.\n\n<b>Was sich überwachen lässt</b>\n🌐 <b>Website.</b> Der Bot ruft die Adresse auf und erwartet die Antwort 200.\n💓 <b>Geplante Aufgabe.</b> Ihr Skript ruft nach jedem erfolgreichen Lauf einen ausgegebenen Link auf. Kommt der Aufruf zu spät, erhalten Sie eine Nachricht.\n🔒 <b>SSL-Zertifikat.</b> Wird täglich geprüft, Warnungen kommen %d und %d Tage vor Ablauf.\n🖥 <b>Server.</b> Ein kleiner Agent meldet die Auslastung von CPU, Speicher und Festplatte. Sie erhalten eine Nachricht, wenn ein Grenzwert überschritten wird oder der Server nichts mehr meldet.\n\nDer kostenlose Tarif umfasst %d Monitore mit einer Prüfung alle %d Minuten.\nSchnellbefehle: /menu, /list, /add.",

		"add.title":  "<b>➕ Neuer Monitor</b>\nWas soll überwacht werden?",
		"list.title": "<b>📋 Meine Monitore</b>\nTippen Sie auf einen Monitor, um Details zu sehen.",
		"list.empty": "<b>📋 Meine Monitore</b>\nHier ist noch nichts. Tippen Sie auf „Monitor hinzufügen“, um den ersten anzulegen.",
		"list.more":  "Angezeigt werden die ersten %d von %d.",

		"lbl.address":         "🔗 <b>Adresse</b>",
		"lbl.interval":        "⏱ <b>Prüfung alle</b>",
		"lbl.signal_interval": "⏱ <b>Signal erwartet alle</b>",
		"lbl.ping_url":        "🔗 <b>Signal-Link</b>",
		"lbl.domain":          "🌍 <b>Domain</b>",
		"lbl.check":           "⏱ <b>Prüfung</b>",
		"lbl.cert_until":      "📅 <b>Gültig bis</b>",
		"lbl.report_interval": "⏱ <b>Bericht alle</b>",
		"lbl.thresholds":      "⚙️ <b>Grenzwerte</b>",
		"lbl.last_report":     "📟 <b>Letzter Bericht</b>",
		"lbl.last_check":      "🕐 <b>Letzte Prüfung</b>",
		"lbl.last_success":    "✅ <b>Letzter Erfolg</b>",

		"st.up":      "In Betrieb",
		"st.down":    "Gestört",
		"st.unknown": "Wartet auf die erste Prüfung",

		"type.http":      "🌐 Website (HTTP)",
		"type.heartbeat": "💓 Geplante Aufgabe",
		"type.ssl":       "🔒 SSL-Zertifikat",
		"type.agent":     "🖥 Server",

		"metric.cpu":  "CPU",
		"metric.ram":  "RAM",
		"metric.disk": "Festplatte",

		"ui.metrics": "CPU %.0f%%, RAM %.0f%%, Festplatte %.0f%%",
		"ui.daily":   "einmal täglich",
		"ui.cert":    "%s, verbleibende Tage: %d",

		"hist.title":    "<b>📊 Verlauf</b>\n%s",
		"hist.stats":    "<b>Letzte %d Tage</b>",
		"hist.nodata":   "Noch keine Daten.",
		"hist.hb_total": "Signale erhalten %d, ausgeblieben %d.",
		"hist.hb_day":   "%s  ✅ %d  ❌ %d",
		"hist.ok_total": "Erfolgsquote %.2f%% (%d von %d Prüfungen).",
		"hist.day":      "%s  %.1f%% von %d Prüfungen",
		"hist.recent":   "<b>Letzte Einträge (%d)</b>",
		"hist.empty":    "Noch keine Einträge.",
		"hist.row":      "%s %s  %s",
		"hist.upsell":   "🔒 Premium enthält %d Tage Verlauf und Statistik.",

		"del.confirm":  "🗑 „%s“ löschen? Der Prüfverlauf wird ebenfalls entfernt.",
		"del.done":     "🗑 Der Monitor wurde gelöscht.",
		"err.notfound": "Monitor nicht gefunden.",

		"thr.title": "<b>⚙️ Grenzwerte für %s</b>\nDie Werte sind in Prozent angegeben. Sie erhalten eine Nachricht, wenn ein Grenzwert in zwei Berichten hintereinander überschritten wird. Tippen Sie auf einen Wert, um ihn zu ändern.",
		"thr.err":   "Geben Sie eine ganze Zahl von 1 bis 100 ein.",
		"thr.bad":   "Ungültiger Parameter. Verwenden Sie cpu=85 ram=90 disk=95 mit Werten von 1 bis 100.",
		"thr.range": "Die Schwellenwerte müssen zwischen 1 und 100 liegen.",
		"wiz.thr":   "<b>⚙️ Grenzwert %s</b>\nSenden Sie eine Zahl von 1 bis 100 (Prozent).",

		"inst.screen": "<b>💻 Agent installieren</b>\nFühren Sie diesen Befehl auf dem Server aus (Linux mit systemd und Root-Rechte erforderlich).\n<code>%s</code>\n🔐 Der Befehl enthält ein geheimes Token, geben Sie ihn nicht weiter.",

		"created.title": "✅ <b>Monitor hinzugefügt</b>\n\n",
		"created.http":  "🌐 Website „%s“\nPrüfung alle %s, die erste Prüfung läuft innerhalb von 30 Sekunden.\nSie werden nach %d fehlgeschlagenen Prüfungen in Folge benachrichtigt.",
		"created.hb":    "💓 Aufgabe „%s“\n\n🔗 <b>Signal-Link</b> (bitte vertraulich behandeln)\n<code>%s</code>\n\nRichten Sie Ihr Skript so ein, dass es nach jedem erfolgreichen Lauf eine GET-Anfrage an diesen Link sendet, mindestens einmal alle %s. Kommt länger als %s nichts an, erhalten Sie eine Nachricht.\n\n<b>Beispiel für cron</b>\n<code>0 3 * * * /path/backup.sh &amp;&amp; curl -fsS -m 10 --retry 3 %s</code>",
		"created.ssl":   "🔒 SSL-Zertifikat „%s“, Domain %s\nPrüfung einmal täglich, die erste läuft innerhalb von 30 Sekunden.\nWarnungen kommen %d und %d Tage vor Ablauf.",
		"created.agent": "🖥 Server „%s“\n\nFühren Sie diesen Befehl auf dem Server aus (Linux mit systemd und Root-Rechte erforderlich).\n<code>%s</code>\n\nDer Agent meldet die Auslastung von Prozessor, Speicher und Festplatte alle %s. Die Standardgrenzwerte betragen %.0f%%, Sie können sie auf der Monitorseite ändern. Sie erhalten eine Nachricht nach %d Berichten in Folge über einem Grenzwert oder wenn %s lang kein Bericht eintrifft.\n🔐 Der Befehl enthält ein geheimes Token, geben Sie ihn nicht weiter.",

		"premium.text":        "<b>⭐ Premium</b>\nFür eine Überwachung, die nie schläft.\n\n✔ bis zu %d Monitore\n✔ Websites alle %d Min. statt alle %d Min. geprüft\n✔ Signale und Berichte ab %d Min.\n✔ Weiterleitung von Alarmen an andere Chats\n✔ Verlauf und Statistik für %d Tage\n\n%d Stars für %d Tage. Eine erneute Zahlung verlängert den Zeitraum.",
		"premium.active":      "✅ Aktiv bis %s.",
		"premium.unavailable": "Der Tarif Premium ist derzeit nicht verfügbar.",
		"premium.expired":     "⭐ Ihr Tarif Premium ist abgelaufen. Es gelten wieder die Grenzen des kostenlosen Tarifs.",

		"chats.free":        "Der kostenlose Tarif leitet Alarme nicht an andere Chats weiter.",
		"chats.free_upsell": "Premium leitet Alarme an andere Chats weiter.",
		"chats.screen":      "<b>💬 Weitere Chats</b>\nAlarme werden in diese Gruppen und Kanäle kopiert.\n\nAktuell %s.",
		"chats.none":        "keine",
		"chats.prompt":      "<b>💬 Weitere Chats</b>\nSenden Sie die IDs von Gruppen oder Kanälen durch Kommas getrennt. Eine ID beginnt mit einem Minuszeichen, zum Beispiel -1001234567890.\nFügen Sie den Bot zuerst zum Chat hinzu und stellen Sie sicher, dass Sie Mitglied sind. Die ID erfahren Sie beim Bot @getidsbot. Höchstens %d Chats.",
		"chats.ok":          "Benachrichtigungen werden in die Chats %s kopiert.",
		"chats.cleared":     "Die weiteren Chats wurden entfernt.",
		"chats.bad":         "Die IDs wurden nicht akzeptiert. Erforderlich sind Nummern von Gruppen oder Kanälen mit Minuszeichen, höchstens %d.",
		"chats.unreachable": "Chat %s ist nicht erreichbar. Fügen Sie den Bot zum Chat hinzu und prüfen Sie die ID.",
		"chats.hello":       "✅ UptimeAnt-Benachrichtigungen sind jetzt mit diesem Chat verbunden.",

		"wiz.title.http":   "🌐 Neuer Website-Monitor",
		"wiz.title.hb":     "💓 Neuer Monitor für eine geplante Aufgabe",
		"wiz.title.ssl":    "🔒 Neuer SSL-Zertifikat-Monitor",
		"wiz.title.ag":     "🖥 Neuer Server-Monitor",
		"wiz.example.http": "Hauptwebsite",
		"wiz.example.hb":   "Datenbanksicherung",
		"wiz.example.ssl":  "Zertifikat der Website",
		"wiz.example.ag":   "Hauptserver",
		"wiz.name":         "<b>%s</b>\nSchritt 1 von 2. Senden Sie einen Namen, zum Beispiel „%s“.",
		"wiz.http":         "<b>🌐 Website-Adresse</b>\nSchritt 2 von 2. Senden Sie die Adresse mit Protokoll, zum Beispiel https://example.com.",
		"wiz.ssl":          "<b>🔒 Domain</b>\nSchritt 2 von 2. Senden Sie die Domain, zum Beispiel example.com. Einen nicht standardmäßigen Port hängen Sie nach einem Doppelpunkt an.",
		"wiz.hb":           "<b>⏱ Signalintervall</b>\nSchritt 2 von 2. Wie oft ruft das Skript den Link auf? Wählen Sie eine Option oder senden Sie eine Anzahl von Minuten.",
		"wiz.ag":           "<b>⏱ Berichtsintervall</b>\nSchritt 2 von 2. Wie oft soll der Server einen Bericht senden? Wählen Sie eine Option oder senden Sie eine Anzahl von Minuten.",
		"wiz.name_empty":   "Der Name darf nicht leer sein.",
		"wiz.num":          "Geben Sie eine Anzahl von Minuten ein.",

		"iv.1":    "1 Min.",
		"iv.5":    "5 Min.",
		"iv.10":   "10 Min.",
		"iv.30":   "30 Min.",
		"iv.60":   "1 Stunde",
		"iv.1440": "1 Tag",

		"err.limit":           "Die Grenze des kostenlosen Tarifs von %d Monitoren ist erreicht.",
		"err.limit_upsell":    " Premium erlaubt bis zu %d.",
		"err.limit_premium":   "Das Premium-Limit von %d Monitoren pro Konto ist erreicht.",
		"err.url_long":        "Die Adresse ist zu lang.",
		"err.addr":            "Die Adresse wurde nicht akzeptiert. %s",
		"err.domain":          "Die Domain wurde nicht akzeptiert. %s",
		"err.interval":        "Ungültiges Intervall. Geben Sie eine Anzahl von Minuten von %d bis %d ein.",
		"err.interval_upsell": " Intervalle unter %d Minuten sind mit Premium verfügbar.",
		"err.save":            "Der Monitor konnte nicht gespeichert werden. Bitte versuchen Sie es erneut.",

		"e.local":     "Lokale Adressen sind nicht zulässig.",
		"e.internal":  "Adressen des internen Netzwerks sind nicht zulässig.",
		"e.nodomain":  "Die Domain wurde nicht gefunden.",
		"e.badurl":    "Ungültige Adresse.",
		"e.scheme":    "Unterstützt werden nur Adressen mit http:// und https://.",
		"e.badport":   "Ungültiger Port.",
		"e.domainfmt": "Geben Sie die Domain im Format example.com an.",

		"use.http":   "Befehlsformat: /add_http Name Adresse\nBeispiel: /add_http Meine Website https://example.com",
		"use.hb":     "Befehlsformat: /add_heartbeat Name Minuten\nBeispiel: /add_heartbeat Sicherung 1440",
		"use.ssl":    "Befehlsformat: /add_ssl Name Domain\nBeispiel: /add_ssl Meine Website example.com",
		"use.agent":  "Befehlsformat: /add_agent Name [Minuten]\nBeispiel: /add_agent Hauptserver 10",
		"use.thr":    "Befehlsformat: /thresholds Nummer cpu=85 ram=90 disk=95\nDie Nummer eines Server-Monitors steht auf dessen Seite.",
		"use.status": "Befehlsformat: /status Nummer",
		"use.remove": "Befehlsformat: /remove Nummer",

		"msg.unknown": "Das habe ich nicht verstanden. Bitte nutzen Sie die Menüschaltflächen.",

		"pay.disabled":   "Die Bezahlung ist derzeit deaktiviert.",
		"pay.support":    "Bei Fragen zur Zahlung und zur Rückerstattung von Stars wenden Sie sich an %s. Nennen Sie Ihre ID %d.",
		"pay.precheck":   "Die Rechnung ist ungültig. Erstellen Sie im Bereich Premium eine neue.",
		"pay.unrecorded": "Die Zahlung ist eingegangen, der Tarif konnte aber nicht aktiviert werden. Wenden Sie sich mit dem Befehl /paysupport an den Support.",
		"pay.ok":         "⭐ Zahlung erhalten. Premium ist aktiv bis %s.",

		"invoice.desc":  "Tarif Premium für %d Tage. Unbegrenzte Monitore, Prüfung jede Minute, Verlauf für %d Tage.",
		"invoice.label": "Premium, %d Tage",
		"invoice.fail":  "Die Rechnung konnte nicht erstellt werden. Bitte versuchen Sie es später erneut.",

		"alert.recovered": "🟢 <b>Wieder in Ordnung</b>\n📌 %s",
		"alert.break":     "⏱ Die Unterbrechung dauerte etwa %s.",
		"alert.monitor":   "📌 %s",
		"alert.addr":      "🔗 %s",
		"alert.last":      "🕐 Letzter Erfolg %s",
		"alert.ssl_far":   "⚠️ Zertifikat läuft bald ab",
		"alert.ssl_near":  "🚨 Zertifikat läuft innerhalb von %d Tagen ab",
		"alert.ssl_body":  "📌 %s\n🌍 %s\n📅 Gültig bis %s, verbleibende Tage: %d\nErneuern Sie das Zertifikat rechtzeitig, sonst warnen Browser Ihre Besucher.",

		"title.http":         "Website nicht erreichbar",
		"title.hb":           "Geplante Aufgabe meldet sich nicht",
		"title.ssl":          "Problem mit dem SSL-Zertifikat",
		"title.agent_silent": "Server meldet sich nicht mehr",
		"title.agent_thr":    "Serverressourcen über dem Grenzwert",

		"d.http_ok":         "HTTP 200, %v ms",
		"d.http_redirected": "HTTP 200 nach Weiterleitung zu %v (%v ms)",
		"d.http_status":     "Der Server antwortete mit HTTP %v",
		"d.http_redirect":   "Der Server antwortete mit HTTP %v und leitete auf %v um. Geben Sie die endgültige Adresse an",
		"d.timeout":         "Keine Antwort innerhalb von %v s",
		"d.badurl":          "Ungültige Adresse",
		"d.net":             "Verbindungsfehler %v",
		"d.silent_sig":      "Kein Signal seit %v Min. bei erwartetem Intervall von %v Min.",
		"d.silent_rep":      "Kein Bericht seit %v Min. bei erwartetem Intervall von %v Min.",
		"d.ping":            "Signal empfangen",
		"d.cert_ok":         "Zertifikat gültig bis %v, verbleibende Tage: %v",
		"d.cert_invalid":    "Das Zertifikat ist ungültig. %v",
		"d.cert_fail":       "Das Zertifikat konnte nicht abgerufen werden. %v",
		"d.agent_ok":        "CPU %v%%, RAM %v%%, Festplatte %v%%",
		"d.agent_back":      "CPU %v%%, RAM %v%%, Festplatte %v%%. Berichte wieder empfangen",
		"d.breach":          "Schwellenwerte überschritten. %v",
		"d.breach_item":     "%v %v%% (Schwellenwert %v%%)",
		"lbl.uptime":        "📈 <b>Letzte 24 Stunden</b>",
		"card.sub":          "%s · %s · Nr. %d",
		"ui.uptime":         "%.1f%% erfolgreich (%d Prüfungen)",
		"ago.never":         "noch nie",
		"ago.now":           "gerade eben",
		"ago.fmt":           "vor %s",
		"layout.short":      "02.01. 15:04",
		"btn.paysupport":    "Support zur Zahlung",
		"refund.done":       "⭐ Ihre Zahlung von %d Stars wurde erstattet. Der Premium-Zeitraum wurde entsprechend verkürzt.",
		"btn.invite":        "Einladen",
		"inv.title":         "<b>🎁 Freunde einladen</b>\nSenden Sie Ihren persönlichen Link. Sobald ein Freund einen Monitor anlegt und eine Woche später noch aktiv ist, erhalten Sie %d Tage Premium, insgesamt höchstens %d Tage.",
		"inv.link":          "Ihr Link:\n<code>%s</code>",
		"inv.stats":         "Freunde mit Monitor: %d   ⭐ Bonustage: %d   Bis zur Grenze: %d",
		"inv.pending":       "Warten auf die Woche: %d",
		"inv.armed":         "🎁 <b>Ein Freund nutzt UptimeAnt</b>\nJemand ist über Ihren Link gekommen und hat einen Monitor angelegt. Ist er in %d Tagen noch aktiv, erhalten Sie %d Tage Premium.",
		"inv.reward":        "⭐ Ein eingeladener Freund hat eine Woche lang überwacht: %d Tage Premium. Bezahlte Einladungen gesamt: %d.",
	})
}
