package main

func init() {
	register("en", map[string]string{
		"layout.datetime": "2006-01-02 15:04",
		"layout.date":     "2006-01-02",
		"layout.day":      "01-02",
		"unit.min":        "min",
		"unit.h":          "h",
		"unit.d":          "d",

		"cmd.menu":     "Main menu",
		"cmd.list":     "My monitors",
		"cmd.add":      "Add monitor",
		"cmd.language": "Language",
		"cmd.help":     "Help",
		"cmd.premium":  "Premium plan",
		"cmd.invite":   "Invite friends",

		"lang.pick": "Select your language\nВыберите язык\nОберіть мову\nSprache wählen\nSeleccione el idioma",

		"btn.menu":          "Main menu",
		"btn.back":          "Back",
		"btn.cancel":        "Cancel",
		"btn.list":          "My monitors",
		"btn.add":           "Add monitor",
		"btn.help":          "Help",
		"btn.premium":       "Premium",
		"btn.language":      "Language",
		"btn.refresh":       "Refresh",
		"btn.history":       "History",
		"btn.thresholds":    "Thresholds",
		"btn.install":       "Install command",
		"btn.delete":        "Delete",
		"btn.tolist":        "To the list",
		"btn.open":          "Open monitor",
		"btn.pay":           "Pay %d Stars",
		"btn.chats":         "Additional chats",
		"btn.change":        "Change",
		"btn.clear":         "Clear",
		"btn.about_premium": "About Premium",
		"btn.t.http":        "Website (HTTP)",
		"btn.t.hb":          "Scheduled task",
		"btn.t.ssl":         "SSL certificate",
		"btn.t.ag":          "Server",
		"btn.thr_cpu":       "CPU %.0f%%",
		"btn.thr_ram":       "RAM %.0f%%",
		"btn.thr_disk":      "Disk %.0f%%",

		"menu.title":   "<b>UptimeAnt</b>\nI watch your websites, scheduled tasks, SSL certificates and servers, and write here the moment something breaks.",
		"menu.none":    "No monitors yet. Add the first one, it takes a minute.",
		"menu.summary": "🟢 Working %d   🔴 Failing %d   ⚪ Waiting %d",

		"help.text": "<b>❓ Help</b>\nUptimeAnt watches your resources and writes here when something fails and when it recovers.\n\n<b>How it works</b>\n1. Press “Add monitor”.\n2. Choose what to watch.\n3. Follow the short prompts.\n\n<b>What can be watched</b>\n🌐 <b>Website.</b> The bot opens the address and expects a 200 response.\n💓 <b>Scheduled task.</b> Your script calls an issued link after each successful run. If a call is late, you get a message.\n🔒 <b>SSL certificate.</b> Checked daily, with warnings %d and %d days before expiry.\n🖥 <b>Server.</b> A small agent reports CPU, memory and disk. You get a message when a limit is crossed or the server goes quiet.\n\nThe free plan includes %d monitors checked every %d minutes.\nQuick commands: /menu, /list, /add.",

		"add.title":  "<b>➕ New monitor</b>\nWhat should I watch?",
		"list.title": "<b>📋 My monitors</b>\nTap a monitor to see details.",
		"list.empty": "<b>📋 My monitors</b>\nNothing here yet. Press “Add monitor” to create the first one.",
		"list.more":  "Showing the first %d of %d.",

		"lbl.address":         "🔗 <b>Address</b>",
		"lbl.interval":        "⏱ <b>Checked every</b>",
		"lbl.signal_interval": "⏱ <b>Signal expected every</b>",
		"lbl.ping_url":        "🔗 <b>Signal link</b>",
		"lbl.domain":          "🌍 <b>Domain</b>",
		"lbl.check":           "⏱ <b>Checked</b>",
		"lbl.cert_until":      "📅 <b>Valid until</b>",
		"lbl.report_interval": "⏱ <b>Report every</b>",
		"lbl.thresholds":      "⚙️ <b>Limits</b>",
		"lbl.last_report":     "📟 <b>Latest report</b>",
		"lbl.last_check":      "🕐 <b>Last check</b>",
		"lbl.last_success":    "✅ <b>Last success</b>",

		"st.up":      "Working",
		"st.down":    "Failing",
		"st.unknown": "Waiting for the first check",

		"type.http":      "🌐 Website (HTTP)",
		"type.heartbeat": "💓 Scheduled task",
		"type.ssl":       "🔒 SSL certificate",
		"type.agent":     "🖥 Server",

		"metric.cpu":  "CPU",
		"metric.ram":  "RAM",
		"metric.disk": "disk",

		"ui.metrics": "CPU %.0f%%, RAM %.0f%%, disk %.0f%%",
		"ui.daily":   "once a day",
		"ui.cert":    "%s, days left: %d",

		"hist.title":    "<b>📊 History</b>\n%s",
		"hist.stats":    "<b>Last %d days</b>",
		"hist.nodata":   "No data yet.",
		"hist.hb_total": "Signals received %d, missed %d.",
		"hist.hb_day":   "%s  ✅ %d  ❌ %d",
		"hist.ok_total": "Success rate %.2f%% (%d of %d checks).",
		"hist.day":      "%s  %.1f%% of %d checks",
		"hist.recent":   "<b>Latest %d records</b>",
		"hist.empty":    "No records yet.",
		"hist.row":      "%s %s  %s",
		"hist.upsell":   "🔒 Premium adds %d days of history and statistics.",

		"del.confirm":  "🗑 Delete “%s”? Its check history will be removed too.",
		"del.done":     "🗑 The monitor has been deleted.",
		"err.notfound": "Monitor not found.",

		"thr.title": "<b>⚙️ Limits for %s</b>\nValues are in percent. You get a message when a limit is exceeded in two reports in a row. Tap a value to change it.",
		"thr.err":   "Enter a whole number from 1 to 100.",
		"thr.bad":   "Invalid parameter. Use cpu=85 ram=90 disk=95 with values from 1 to 100.",
		"thr.range": "Threshold values must be between 1 and 100.",
		"wiz.thr":   "<b>⚙️ %s limit</b>\nSend a number from 1 to 100 (percent).",

		"inst.screen": "<b>💻 Install the agent</b>\nRun this command on the server (Linux with systemd, root access required).\n<code>%s</code>\n🔐 The command contains a secret token, keep it private.",

		"created.title": "✅ <b>Monitor added</b>\n\n",
		"created.http":  "🌐 Website “%s”\nChecked every %s, the first check runs within 30 seconds.\nYou will be notified after %d failed checks in a row.",
		"created.hb":    "💓 Task “%s”\n\n🔗 <b>Signal link</b> (keep it private)\n<code>%s</code>\n\nMake your script send a GET request to this link after every successful run, at least once every %s. If nothing arrives for %s, you will get a message.\n\n<b>Cron example</b>\n<code>0 3 * * * /path/backup.sh &amp;&amp; curl -fsS -m 10 --retry 3 %s</code>",
		"created.ssl":   "🔒 SSL certificate “%s”, domain %s\nChecked once a day, the first check runs within 30 seconds.\nWarnings arrive %d and %d days before expiry.",
		"created.agent": "🖥 Server “%s”\n\nRun this command on the server (Linux with systemd, root access required).\n<code>%s</code>\n\nThe agent reports CPU, memory and disk load every %s. Default limits are %.0f%%, you can change them on the monitor page. You will be notified after %d reports in a row over a limit, or if no report arrives for %s.\n🔐 The command contains a secret token, keep it private.",

		"premium.text":        "<b>⭐ Premium</b>\nFor monitoring that never sleeps.\n\n✔ up to %d monitors\n✔ websites checked every %d min instead of %d\n✔ signals and reports from %d min\n✔ alerts forwarded to other chats\n✔ %d days of history and statistics\n\n%d Stars for %d days. Paying again extends the period.",
		"premium.active":      "✅ Active until %s.",
		"premium.unavailable": "The Premium plan is currently unavailable.",
		"premium.expired":     "⭐ Your Premium plan has ended. Free plan limits apply again.",

		"chats.free":        "The free plan does not forward alerts to other chats.",
		"chats.free_upsell": "Premium forwards alerts to other chats.",
		"chats.screen":      "<b>💬 Additional chats</b>\nAlerts are duplicated to these groups and channels.\n\nCurrently %s.",
		"chats.none":        "none",
		"chats.prompt":      "<b>💬 Additional chats</b>\nSend group or channel IDs separated by commas. An ID starts with a minus sign, for example -1001234567890.\nAdd the bot to the chat first and make sure you are a member. You can look up an ID with the @getidsbot bot. Up to %d chats.",
		"chats.ok":          "Notifications will be duplicated to the chats %s.",
		"chats.cleared":     "Additional chats have been removed.",
		"chats.bad":         "The IDs were not accepted. Group or channel numbers with a minus sign are required, up to %d.",
		"chats.unreachable": "Chat %s is unavailable. Add the bot to the chat and check the ID.",
		"chats.hello":       "✅ UptimeAnt alerts are now connected to this chat.",

		"wiz.title.http":   "🌐 New website monitor",
		"wiz.title.hb":     "💓 New scheduled task monitor",
		"wiz.title.ssl":    "🔒 New SSL certificate monitor",
		"wiz.title.ag":     "🖥 New server monitor",
		"wiz.example.http": "Main website",
		"wiz.example.hb":   "Database backup",
		"wiz.example.ssl":  "Site certificate",
		"wiz.example.ag":   "Main server",
		"wiz.name":         "<b>%s</b>\nStep 1 of 2. Send a name, for example “%s”.",
		"wiz.http":         "<b>🌐 Website address</b>\nStep 2 of 2. Send the address with the protocol, for example https://example.com.",
		"wiz.ssl":          "<b>🔒 Domain</b>\nStep 2 of 2. Send the domain, for example example.com. Add a non-standard port after a colon.",
		"wiz.hb":           "<b>⏱ Signal interval</b>\nStep 2 of 2. How often will the script call the link? Pick an option or send a number of minutes.",
		"wiz.ag":           "<b>⏱ Report interval</b>\nStep 2 of 2. How often should the server report? Pick an option or send a number of minutes.",
		"wiz.name_empty":   "The name cannot be empty.",
		"wiz.num":          "Enter a number of minutes.",

		"iv.1":    "1 min",
		"iv.5":    "5 min",
		"iv.10":   "10 min",
		"iv.30":   "30 min",
		"iv.60":   "1 hour",
		"iv.1440": "1 day",

		"err.limit":           "The free plan limit of %d monitors has been reached.",
		"err.limit_upsell":    " Premium allows up to %d.",
		"err.limit_premium":   "The Premium limit of %d monitors per account has been reached.",
		"err.url_long":        "The address is too long.",
		"err.addr":            "The address was not accepted. %s",
		"err.domain":          "The domain was not accepted. %s",
		"err.interval":        "Invalid interval. Enter a number of minutes from %d to %d.",
		"err.interval_upsell": " Intervals shorter than %d minutes are available on Premium.",
		"err.save":            "The monitor could not be saved. Please try again.",

		"e.local":     "Local addresses are not allowed.",
		"e.internal":  "Internal network addresses are not allowed.",
		"e.nodomain":  "The domain was not found.",
		"e.badurl":    "Invalid address.",
		"e.scheme":    "Only http:// and https:// addresses are supported.",
		"e.badport":   "Invalid port.",
		"e.domainfmt": "Enter the domain in the format example.com.",

		"use.http":   "Command format: /add_http name address\nExample: /add_http My site https://example.com",
		"use.hb":     "Command format: /add_heartbeat name minutes\nExample: /add_heartbeat Backup 1440",
		"use.ssl":    "Command format: /add_ssl name domain\nExample: /add_ssl My site example.com",
		"use.agent":  "Command format: /add_agent name [minutes]\nExample: /add_agent Main server 10",
		"use.thr":    "Command format: /thresholds id cpu=85 ram=90 disk=95\nThe ID of a server monitor is shown on its page.",
		"use.status": "Command format: /status id",
		"use.remove": "Command format: /remove id",

		"msg.unknown": "I did not understand that. Please use the menu buttons.",

		"pay.disabled":   "Payment is currently disabled.",
		"pay.support":    "For payment and Stars refund questions contact %s. Include your ID %d.",
		"pay.precheck":   "The invoice is not valid. Create a new one in the Premium section.",
		"pay.unrecorded": "The payment was received, but the plan could not be activated. Contact support with the /paysupport command.",
		"pay.ok":         "⭐ Payment received. Premium is active until %s.",

		"invoice.desc":  "Premium plan for %d days. Unlimited monitors, checks every minute, %d days of history.",
		"invoice.label": "Premium, %d days",
		"invoice.fail":  "The invoice could not be created. Please try again later.",

		"alert.recovered": "🟢 <b>Back to normal</b>\n📌 %s",
		"alert.break":     "⏱ The interruption lasted about %s.",
		"alert.monitor":   "📌 %s",
		"alert.addr":      "🔗 %s",
		"alert.last":      "🕐 Last success %s",
		"alert.ssl_far":   "⚠️ Certificate expires soon",
		"alert.ssl_near":  "🚨 Certificate expires within %d days",
		"alert.ssl_body":  "📌 %s\n🌍 %s\n📅 Valid until %s, days left: %d\nRenew the certificate in time, otherwise browsers will warn your visitors.",

		"title.http":         "Website is down",
		"title.hb":           "A scheduled task went silent",
		"title.ssl":          "SSL certificate problem",
		"title.agent_silent": "Server stopped reporting",
		"title.agent_thr":    "Server resources over the limit",

		"d.http_ok":         "HTTP 200, %v ms",
		"d.http_redirected": "HTTP 200 after a redirect to %v (%v ms)",
		"d.http_status":     "The server returned HTTP %v",
		"d.http_redirect":   "The server returned HTTP %v with a redirect to %v. Specify the final address",
		"d.timeout":         "No response within %v s",
		"d.badurl":          "Invalid address",
		"d.net":             "Connection error %v",
		"d.silent_sig":      "No signal for %v min with an expected interval of %v min",
		"d.silent_rep":      "No report for %v min with an expected interval of %v min",
		"d.ping":            "Signal received",
		"d.cert_ok":         "Certificate valid until %v, days left: %v",
		"d.cert_invalid":    "The certificate is not valid. %v",
		"d.cert_fail":       "Could not retrieve the certificate. %v",
		"d.agent_ok":        "CPU %v%%, RAM %v%%, disk %v%%",
		"d.agent_back":      "CPU %v%%, RAM %v%%, disk %v%%. Reports resumed",
		"d.breach":          "Thresholds exceeded. %v",
		"d.breach_item":     "%v %v%% (threshold %v%%)",
		"lbl.uptime":        "📈 <b>Last 24 hours</b>",
		"card.sub":          "%s · %s · ID %d",
		"ui.uptime":         "%.1f%% successful (%d checks)",
		"ago.never":         "never",
		"ago.now":           "just now",
		"ago.fmt":           "%s ago",
		"layout.short":      "01-02 15:04",
		"btn.paysupport":    "Payment support",
		"refund.done":       "⭐ Your payment of %d Stars has been refunded. The Premium period was shortened accordingly.",
		"btn.invite":        "Invite",
		"inv.title":         "<b>🎁 Invite friends</b>\nSend your personal link. When a friend sets up a monitor and is still using the bot a week later, you get %d days of Premium, %d days at most in total.",
		"inv.link":          "Your link:\n<code>%s</code>",
		"inv.stats":         "Friends with a monitor: %d   ⭐ Bonus days: %d   Left to the limit: %d",
		"inv.pending":       "Waiting for the week to pass: %d",
		"inv.armed":         "🎁 <b>A friend is using UptimeAnt</b>\nSomeone came through your link and set up a monitor. If they are still active in %d days, you get %d days of Premium.",
		"inv.reward":        "⭐ A friend you invited kept watching their monitors for a week: %d days of Premium. Paid invites in total: %d.",
	})
}
