package main

func init() {
	register("es", map[string]string{
		"layout.datetime": "02/01/2006 15:04",
		"layout.date":     "02/01/2006",
		"layout.day":      "02/01",
		"unit.min":        "min",
		"unit.h":          "h",
		"unit.d":          "d",

		"cmd.menu":     "Menú principal",
		"cmd.list":     "Mis pulsos",
		"cmd.add":      "Añadir pulso",
		"cmd.language": "Idioma",
		"cmd.help":     "Ayuda",
		"cmd.premium":  "Plan Premium",
		"cmd.invite":   "Invitar a un amigo",

		"lang.pick": "Select your language\nВыберите язык\nОберіть мову\nSprache wählen\nSeleccione el idioma",

		"btn.menu":          "Menú principal",
		"btn.back":          "Atrás",
		"btn.cancel":        "Cancelar",
		"btn.list":          "Mis pulsos",
		"btn.add":           "Añadir pulso",
		"btn.help":          "Ayuda",
		"btn.premium":       "Premium",
		"btn.language":      "Idioma",
		"btn.refresh":       "Actualizar",
		"btn.history":       "Historial",
		"btn.thresholds":    "Umbrales",
		"btn.install":       "Comando de instalación",
		"btn.delete":        "Eliminar",
		"btn.tolist":        "A la lista",
		"btn.open":          "Abrir pulso",
		"btn.pay":           "Pagar %d Stars",
		"btn.chats":         "Chats adicionales",
		"btn.change":        "Cambiar",
		"btn.clear":         "Borrar",
		"btn.about_premium": "Sobre Premium",
		"btn.t.http":        "Sitio web (HTTP)",
		"btn.t.hb":          "Tarea programada",
		"btn.t.ssl":         "Certificado SSL",
		"btn.t.ag":          "Servidor",
		"btn.thr_cpu":       "CPU %.0f%%",
		"btn.thr_ram":       "RAM %.0f%%",
		"btn.thr_disk":      "Disco %.0f%%",

		"menu.title":   "<b>PulseCheck</b>\nVigilo sus sitios web, tareas programadas, certificados SSL y servidores, y le escribo aquí en cuanto algo falle.",
		"menu.none":    "Todavía no tiene pulsos. Añada el primero, lleva aproximadamente un minuto.",
		"menu.summary": "🟢 Funcionan %d   🔴 Con fallo %d   ⚪ En espera %d",

		"help.text": "<b>❓ Ayuda</b>\nPulseCheck vigila sus recursos y escribe en este chat cuando algo falla y cuando todo vuelve a funcionar.\n\n<b>Cómo funciona</b>\n1. Pulse «Añadir pulso».\n2. Elija qué desea vigilar.\n3. Siga las breves indicaciones.\n\n<b>Qué se puede vigilar</b>\n🌐 <b>Sitio web.</b> El bot abre la dirección y espera una respuesta 200.\n💓 <b>Tarea programada.</b> Su script solicita un enlace asignado tras cada ejecución correcta. Si la llamada se retrasa, recibirá un mensaje.\n🔒 <b>Certificado SSL.</b> Se comprueba cada día y se avisa %d y %d días antes del vencimiento.\n🖥 <b>Servidor.</b> Un pequeño agente informa de la carga del procesador, la memoria y el disco. Recibirá un mensaje si se supera un límite o el servidor deja de responder.\n\nEl plan gratuito incluye %d pulsos con una comprobación cada %d minutos.\nComandos rápidos: /menu, /list, /add.",

		"add.title":  "<b>➕ Nuevo pulso</b>\n¿Qué desea vigilar?",
		"list.title": "<b>📋 Mis pulsos</b>\nPulse un pulso para ver los detalles.",
		"list.empty": "<b>📋 Mis pulsos</b>\nAquí todavía no hay nada. Pulse «Añadir pulso» para crear el primero.",
		"list.more":  "Se muestran los primeros %d de %d.",

		"lbl.address":         "🔗 <b>Dirección</b>",
		"lbl.interval":        "⏱ <b>Comprobación cada</b>",
		"lbl.signal_interval": "⏱ <b>Señal esperada cada</b>",
		"lbl.ping_url":        "🔗 <b>Enlace de señales</b>",
		"lbl.domain":          "🌍 <b>Dominio</b>",
		"lbl.check":           "⏱ <b>Comprobación</b>",
		"lbl.cert_until":      "📅 <b>Válido hasta</b>",
		"lbl.report_interval": "⏱ <b>Informe cada</b>",
		"lbl.thresholds":      "⚙️ <b>Límites</b>",
		"lbl.last_report":     "📟 <b>Último informe</b>",
		"lbl.last_check":      "🕐 <b>Última comprobación</b>",
		"lbl.last_success":    "✅ <b>Último éxito</b>",

		"st.up":      "Funciona",
		"st.down":    "Con fallo",
		"st.unknown": "Pendiente de la primera comprobación",

		"type.http":      "🌐 Sitio web (HTTP)",
		"type.heartbeat": "💓 Tarea programada",
		"type.ssl":       "🔒 Certificado SSL",
		"type.agent":     "🖥 Servidor",

		"metric.cpu":  "CPU",
		"metric.ram":  "RAM",
		"metric.disk": "disco",

		"ui.metrics": "CPU %.0f%%, RAM %.0f%%, disco %.0f%%",
		"ui.daily":   "una vez al día",
		"ui.cert":    "%s, días restantes: %d",

		"hist.title":    "<b>📊 Historial</b>\n%s",
		"hist.stats":    "<b>Últimos %d días</b>",
		"hist.nodata":   "Todavía no hay datos.",
		"hist.hb_total": "Señales recibidas %d, omitidas %d.",
		"hist.hb_day":   "%s  ✅ %d  ❌ %d",
		"hist.ok_total": "Tasa de éxito %.2f%% (%d de %d comprobaciones).",
		"hist.day":      "%s  %.1f%% de %d comprobaciones",
		"hist.recent":   "<b>Últimos registros (%d)</b>",
		"hist.empty":    "Todavía no hay registros.",
		"hist.row":      "%s %s  %s",
		"hist.upsell":   "🔒 El historial y las estadísticas diarias de %d días forman parte de Premium.",

		"del.confirm":  "🗑 ¿Eliminar «%s»? El historial de comprobaciones también se eliminará.",
		"del.done":     "🗑 El pulso se ha eliminado.",
		"err.notfound": "Pulso no encontrado.",

		"thr.title": "<b>⚙️ Límites de %s</b>\nLos valores están en porcentaje. Recibirá un mensaje si se supera un límite en dos informes seguidos. Pulse un valor para cambiarlo.",
		"thr.err":   "Introduzca un número entero del 1 al 100.",
		"thr.bad":   "Parámetro no válido. Utilice cpu=85 ram=90 disk=95 con valores del 1 al 100.",
		"thr.range": "Los valores de los umbrales deben estar entre 1 y 100.",
		"wiz.thr":   "<b>⚙️ Límite de %s</b>\nEnvíe un número del 1 al 100 (porcentaje).",

		"inst.screen": "<b>💻 Instalar el agente</b>\nEjecute este comando en el servidor (se necesitan Linux con systemd y permisos de root).\n<code>%s</code>\n🔐 El comando contiene un token secreto, no lo comparta.",

		"created.title": "✅ <b>Pulso añadido</b>\n\n",
		"created.http":  "🌐 Sitio web «%s»\nComprobación cada %s; la primera se realiza en 30 segundos.\nSe le avisará tras %d comprobaciones fallidas seguidas.",
		"created.hb":    "💓 Tarea «%s»\n\n🔗 <b>Enlace de señales</b> (manténgalo en privado)\n<code>%s</code>\n\nConfigure su script para que envíe una solicitud GET a este enlace tras cada ejecución correcta, al menos una vez cada %s. Si no llega nada durante %s, recibirá un mensaje.\n\n<b>Ejemplo para cron</b>\n<code>0 3 * * * /path/backup.sh &amp;&amp; curl -fsS -m 10 --retry 3 %s</code>",
		"created.ssl":   "🔒 Certificado SSL «%s», dominio %s\nSe comprueba una vez al día; la primera comprobación se realiza en 30 segundos.\nLos avisos llegarán %d y %d días antes del vencimiento.",
		"created.agent": "🖥 Servidor «%s»\n\nEjecute este comando en el servidor (se necesitan Linux con systemd y permisos de root).\n<code>%s</code>\n\nEl agente informa de la carga del procesador, la memoria y el disco cada %s. Los límites predeterminados son %.0f%%; puede cambiarlos en la página del pulso. Recibirá un mensaje tras %d informes seguidos por encima de un límite, o si no llega ningún informe durante %s.\n🔐 El comando contiene un token secreto, no lo comparta.",

		"premium.text":        "<b>⭐ Premium</b>\nPara una supervisión que nunca duerme.\n\n✔ número ilimitado de pulsos\n✔ sitios web comprobados cada %d min en lugar de cada %d\n✔ señales e informes desde %d min\n✔ alertas reenviadas a otros chats\n✔ historial y estadísticas de %d días\n\n%d Stars por %d días. Un nuevo pago amplía el periodo.",
		"premium.active":      "✅ Activo hasta %s.",
		"premium.unavailable": "El plan Premium no está disponible en este momento.",
		"premium.expired":     "⭐ Su plan Premium ha terminado. Vuelven a aplicarse los límites del plan gratuito.",

		"chats.free":        "El reenvío de notificaciones a otros chats no está disponible en el plan gratuito.",
		"chats.free_upsell": "El reenvío de notificaciones a otros chats está disponible en el plan Premium.",
		"chats.screen":      "<b>💬 Chats adicionales</b>\nLas alertas se duplican en estos grupos y canales.\n\nActualmente %s.",
		"chats.none":        "ninguno",
		"chats.prompt":      "<b>💬 Chats adicionales</b>\nEnvíe los identificadores de grupos o canales separados por comas. Un identificador empieza con un signo menos, por ejemplo -1001234567890.\nAñada primero el bot al chat y asegúrese de ser miembro. Puede averiguar el identificador con el bot @getidsbot. Máximo %d chats.",
		"chats.ok":          "Las notificaciones se duplicarán en los chats %s.",
		"chats.cleared":     "Los chats adicionales se han eliminado.",
		"chats.bad":         "No se aceptaron los identificadores. Se necesitan números de grupos o canales con signo menos, máximo %d.",
		"chats.unreachable": "El chat %s no está disponible. Añada el bot al chat y compruebe el identificador.",
		"chats.hello":       "✅ Las notificaciones de PulseCheck ya están conectadas a este chat.",

		"wiz.title.http":   "🌐 Nuevo pulso de sitio web",
		"wiz.title.hb":     "💓 Nuevo pulso de tarea programada",
		"wiz.title.ssl":    "🔒 Nuevo pulso de certificado SSL",
		"wiz.title.ag":     "🖥 Nuevo pulso de servidor",
		"wiz.example.http": "Sitio principal",
		"wiz.example.hb":   "Copia de seguridad",
		"wiz.example.ssl":  "Certificado del sitio",
		"wiz.example.ag":   "Servidor principal",
		"wiz.name":         "<b>%s</b>\nPaso 1 de 2. Envíe un nombre, por ejemplo «%s».",
		"wiz.http":         "<b>🌐 Dirección del sitio</b>\nPaso 2 de 2. Envíe la dirección con el protocolo, por ejemplo https://example.com.",
		"wiz.ssl":          "<b>🔒 Dominio</b>\nPaso 2 de 2. Envíe el dominio, por ejemplo example.com. Si usa un puerto no estándar, añádalo después de dos puntos.",
		"wiz.hb":           "<b>⏱ Intervalo de señales</b>\nPaso 2 de 2. ¿Con qué frecuencia llamará el script al enlace? Elija una opción o envíe un número de minutos.",
		"wiz.ag":           "<b>⏱ Intervalo de informes</b>\nPaso 2 de 2. ¿Con qué frecuencia debe informar el servidor? Elija una opción o envíe un número de minutos.",
		"wiz.name_empty":   "El nombre no puede estar vacío.",
		"wiz.num":          "Introduzca un número de minutos.",

		"iv.1":    "1 min",
		"iv.5":    "5 min",
		"iv.10":   "10 min",
		"iv.30":   "30 min",
		"iv.60":   "1 hora",
		"iv.1440": "1 día",

		"err.limit":           "Se ha alcanzado el límite del plan gratuito de %d pulsos.",
		"err.limit_upsell":    " Para quitar el límite, contrate Premium.",
		"err.url_long":        "La dirección es demasiado larga.",
		"err.addr":            "No se aceptó la dirección. %s",
		"err.domain":          "No se aceptó el dominio. %s",
		"err.interval":        "Intervalo no válido. Introduzca un número de minutos del %d al %d.",
		"err.interval_upsell": " Los intervalos inferiores a %d minutos están disponibles en Premium.",
		"err.save":            "No se pudo guardar el pulso. Inténtelo de nuevo.",

		"e.local":     "No se permiten direcciones locales.",
		"e.internal":  "No se permiten direcciones de la red interna.",
		"e.nodomain":  "No se encontró el dominio.",
		"e.badurl":    "Dirección no válida.",
		"e.scheme":    "Solo se admiten direcciones http:// y https://.",
		"e.badport":   "Puerto no válido.",
		"e.domainfmt": "Indique el dominio con el formato example.com.",

		"use.http":   "Formato del comando: /add_http nombre dirección\nEjemplo: /add_http Mi sitio https://example.com",
		"use.hb":     "Formato del comando: /add_heartbeat nombre minutos\nEjemplo: /add_heartbeat Copia 1440",
		"use.ssl":    "Formato del comando: /add_ssl nombre dominio\nEjemplo: /add_ssl Mi sitio example.com",
		"use.agent":  "Formato del comando: /add_agent nombre [minutos]\nEjemplo: /add_agent Servidor principal 10",
		"use.thr":    "Formato del comando: /thresholds número cpu=85 ram=90 disk=95\nEl número de un pulso de servidor figura en su página.",
		"use.status": "Formato del comando: /status número",
		"use.remove": "Formato del comando: /remove número",

		"msg.unknown": "No he entendido el mensaje. Utilice los botones del menú.",

		"pay.disabled":   "El pago está desactivado en este momento.",
		"pay.support":    "Para consultas sobre pagos y reembolsos de Stars, contacte con %s. Indique su identificador %d.",
		"pay.precheck":   "La factura no es válida. Cree una nueva en la sección Premium.",
		"pay.unrecorded": "Se recibió el pago, pero no se pudo activar el plan. Contacte con el soporte mediante el comando /paysupport.",
		"pay.ok":         "⭐ Pago recibido. Premium está activo hasta %s.",

		"invoice.desc":  "Plan Premium por %d días. Pulsos ilimitados, comprobaciones cada minuto, historial de %d días.",
		"invoice.label": "Premium, %d días",
		"invoice.fail":  "No se pudo crear la factura. Inténtelo de nuevo más tarde.",

		"alert.recovered": "🟢 <b>Todo vuelve a la normalidad</b>\n📌 %s",
		"alert.break":     "⏱ La interrupción duró aproximadamente %s.",
		"alert.pulse":     "📌 %s",
		"alert.addr":      "🔗 %s",
		"alert.last":      "🕐 Último éxito %s",
		"alert.ssl_far":   "⚠️ El certificado caduca pronto",
		"alert.ssl_near":  "🚨 El certificado caduca en menos de %d días",
		"alert.ssl_body":  "📌 %s\n🌍 %s\n📅 Válido hasta %s, días restantes: %d\nRenueve el certificado a tiempo; de lo contrario, los navegadores avisarán a sus visitantes.",

		"title.http":         "Sitio web no disponible",
		"title.hb":           "Una tarea programada no da señales",
		"title.ssl":          "Problema con el certificado SSL",
		"title.agent_silent": "El servidor dejó de informar",
		"title.agent_thr":    "Recursos del servidor por encima del límite",

		"d.http_ok":       "HTTP 200, %v ms",
		"d.http_status":   "El servidor devolvió HTTP %v",
		"d.http_redirect": "El servidor devolvió HTTP %v con redirección a %v. Indique la dirección final",
		"d.timeout":       "Sin respuesta en %v s",
		"d.badurl":        "Dirección no válida",
		"d.net":           "Error de conexión %v",
		"d.silent_sig":    "Sin señal durante %v min con un intervalo esperado de %v min",
		"d.silent_rep":    "Sin informe durante %v min con un intervalo esperado de %v min",
		"d.ping":          "Señal recibida",
		"d.cert_ok":       "Certificado válido hasta %v, días restantes: %v",
		"d.cert_invalid":  "El certificado no es válido. %v",
		"d.cert_fail":     "No se pudo obtener el certificado. %v",
		"d.agent_ok":      "CPU %v%%, RAM %v%%, disco %v%%",
		"d.agent_back":    "CPU %v%%, RAM %v%%, disco %v%%. Los informes se han reanudado",
		"d.breach":        "Se superaron los umbrales. %v",
		"d.breach_item":   "%v %v%% (umbral %v%%)",
		"lbl.uptime":      "📈 <b>Últimas 24 horas</b>",
		"card.sub":        "%s · %s · n.º %d",
		"ui.uptime":       "%.1f%% correctas (%d comprobaciones)",
		"ago.never":       "nunca",
		"ago.now":         "justo ahora",
		"ago.fmt":         "hace %s",
		"layout.short":    "02/01 15:04",
		"btn.paysupport":  "Soporte de pagos",
		"refund.done":     "⭐ Se ha reembolsado su pago de %d Stars. El periodo Premium se ha reducido en consecuencia.",
		"btn.invite":      "Invitar",
		"inv.title":       "<b>🎁 Invitar amigos</b>\nEnvía tu enlace personal. Cuando el amigo invitado añada su primer pulso, recibes %d días de Premium, %d días como máximo en total.",
		"inv.link":        "Tu enlace:\n<code>%s</code>",
		"inv.stats":       "Amigos con pulso: %d   ⭐ Días de bonificación: %d   Hasta el límite: %d",
		"inv.reward":      "⭐ Un amigo invitado ha añadido su primer pulso: %d días de Premium. Invitados en total: %d.",
	})
}
